### ISSUE TITLE
Move mention of two jabber clients to later in the document

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#7]
A reviewer pointed out that this bullet might seem a burden for some newcomers:

```
It can also be helpful to run two separate Jabber clients connected to two separate Jabber servers, to prevent delays if one of the servers experiences an outage during the session.
```

I think this a useful tip to include, but I agree that it might put some newcomers off.  Perhaps we move it as well as the final bullet in section 5.3 about measuring lag time to a new section on "Advanced Tips".  I have a couple of ideas for text.

**Comment by stpeter** [comment]
Added a new section:
1.  Advanced Tips
   
   It can be helpful to run two separate Jabber clients connected to two
   separate Jabber servers, in order to prevent delays if one of the
   servers experiences an outage during the session (yes, it has
   happened).
   
   If you have a chance to do so, you may want to measure the lag time
   between when something is said in the physical room and when it is
   heard on the audio stream and then let the remote participants know
   the length of the delay.  This could be accomplished by either
   listening to the audio stream yourself or working with a remote
   participant who you know is on the audio stream.

However other suggestions are welcome @danyork :-)
