### ISSUE TITLE
Pointer to a Jabber starter guide?

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#9]
A reviewer provided this comment:

---

I would also suggest declaring basic Jabber “how to” outside the scope of this guide, but providing a pointer to such a resource in case the reader is really a newbie.

---

It's an interesting idea.  You could see someone being interested in finding out about being a jabber scribe (because they keep hearing that "we can't start without a jabber scribe" and wonder if this is how they can help) but perhaps not knowing how to get started.    Is there a place we could point them to that was neutral?

**Comment by danyork** [comment]
We received another comment from a reviewer suggesting that we provide something that points people to how to get a Jabber account if they don't have one.

**Comment by stpeter** [comment]
We don't really have such a page anywhere that I know of, in part because the particulars differ depending on which client you use. There is a bit of information that I wrote ages ago for http://www.ietf.org/jabber/ and we could expand that slightly if needed.

**Comment by stpeter** [comment]
Added this section:

6.1.  Getting Set Up with Jabber

   An overview of the IETF Jabber service can be found at <http://
   www.ietf.org/jabber/>.  Many common instant messaging clients support
   the Jabber/XMPP protocols, and at the time of writing a list of such
   clients can be found at http://xmpp.org/xmpp-software/clients/.
   Because the IETF Jabber service provides chatrooms only and does not
   enable direct registration of user accounts, you will need to create
   a user account at another service; one list of such services can be
   found at https://xmpp.net/directory.php.  Not all clients support
   the ability to join a chatroom, so you might want to test your
   preferred software in advance of the meeting (the
   hallway@jabber.ietf.org room is a good place to test).  Although the
   exact user interface for joining a chatroom depends on the software
   you are using, typically such software will have a "join room" option
   that prompts you to provide the entire room address (e.g.,
   "hallway@jabber.ietf.org") or separately provide the name of the room
   (e.g., "hallway") and the domain of the chatroom service (e.g.,
   "jabber.ietf.org").  Asking your fellow IETF participants about their
   preferred software applications can be a good way to learn about
   Jabber/XMPP clients that you might want to use.
